spring:
  datasource:
    url: jdbc:h2:file:C:\JavaLessons\alfa-bank-task/h2/db/db;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: warn
    com.github.peshkovm: debug
