DROP TABLE IF EXISTS ITEM CASCADE;
DROP TABLE IF EXISTS BOX CASCADE;


CREATE TABLE BOX
(
    ID           INTEGER PRIMARY KEY,
    CONTAINED_IN INTEGER
);

CREATE TABLE ITEM
(
    ID           INTEGER PRIMARY KEY,
    CONTAINED_IN INTEGER REFERENCES BOX (ID),
    COLOR        VARCHAR(100)
);
